channels:
- conda-forge
dependencies:
- python=3.12.5
- pip
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.1.0
  - numpy==2.1.2
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - skfolio==0.4.2
  - xarray==2024.9.0
name: mlflow-env
